#!/bin/bash

scripts/clean
mkdir build
DANKGRINDER="dankgrinder"
CANDY="candy"

if [ "${GOOS}" = "windows" ]; then
  DANKGRINDER="${DANKGRINDER}.exe"
  CANDY="${CANDY}.exe"
fi

(cd cmd/dankgrinder; go build -v -o "../../build/${DANKGRINDER}" .)
(cd cmd/candy; go build -v -o "../../build/${CANDY}" .)
