#!/bin/bash

scripts/clean
mkdir build
DANKGRINDER="dankgrinder"
DANKSELLER="dankseller"

if [ "${GOOS}" = "windows" ]; then
  DANKGRINDER="${DANKGRINDER}.exe"
  DANKSELLER="${DANKSELLER}.exe"
fi

(cd cmd/dankgrinder; go build -v -o "../../build/${DANKGRINDER}" .)
(cd cmd/dankseller; go build -v -o "../../build/${DANKSELLER}" .)
