#!/bin/bash

scripts/clean
mkdir build
DANKGRINDER="dankgrinder"
DANKCURATOR="dankcurator"

if [ "${GOOS}" = "windows" ]; then
  DANKGRINDER="${DANKGRINDER}.exe"
  DANKCURATOR="${DANKCURATOR}.exe"
fi

(cd cmd/dankgrinder; go build -v -o "../../build/${DANKGRINDER}" .)
(cd cmd/dankcurator; go build -v -o "../../build/${DANKCURATOR}" .)
