#!/bin/bash

scripts/clean
source scripts/variables
mkdir release

for OS in "windows" "darwin" "linux"; do
  DIR="release/dankgrinder-${VERSION}-${OS}-amd64"
  DANKGRINDER="dankgrinder"
  DANKCURATOR="dankcurator"

  if [ "${OS}" = "windows" ]; then
    DANKGRINDER="${DANKGRINDER}.exe"
    DANKCURATOR="${DANKCURATOR}.exe"
  fi

  mkdir "${DIR}"
  cp config.yml "${DIR}"
  (cd cmd/dankgrinder || exit; GOOS=${OS} GOARCH=amd64 go build -ldflags "-w -s" -v -o "../../${DIR}/${DANKGRINDER}" .)
  (cd cmd/dankcurator || exit; GOOS=${OS} GOARCH=amd64 go build -ldflags "-w -s" -v -o "../../${DIR}/${DANKCURATOR}" .)
  zip -vr9j "${DIR}".zip "${DIR}"/*
  rm -rf "${DIR}"
done
